### ISSUE TITLE
Intellicenter integration stopped working on 2025.1.0

### ISSUE THREAD

**Issue by Jobsa** [jlvaillant/intellicenter#81]
After upgrading to 2025.1.0 the Intellicenter integration notes 'Not loaded'.  Same result after restarts.  Core log:

Logger: homeassistant.config_entries
Source: config_entries.py:3314
First occurred: January 3, 2025 at 6:18:41 PM (60 occurrences)
Last logged: 8:32:50 PM
Error occurred loading flow for integration intellicenter: cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by ragaimeena** [comment]
did you figure this out?

**Comment by btli** [comment]
Seems related to this:[ Remove deprecated supported features warning in LightEntity #132371](https://github.com/home-assistant/core/pull/132371)

```
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:608
integration: Light (documentation, issues)
First occurred: 6:17:01 PM (3 occurrences)
Last logged: 6:17:01 PM

Error adding entity None for domain light with platform intellicenter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by Jobsa** [comment]
No resolution yet.  Issue persists on 2025.1.1.  I received a notification from @blink that doesn't appear on this thread suggesting that the issue could be related to [Issue #132371](https://github.com/home-assistant/core/pull/132371).  That issue relates to deprecation of integers for supported_features.  Not sure if that is the case or not.  Will need the owner to weigh in.    @jlvaillant, great work on this integration, including acheiving 'gold quality' status.  Hoping you can take a look when time permits.

**Comment by Jobsa** [comment]
Stumbled across what is more likely the issue... [Issue #108991](https://github.com/home-assistant/core/issues/108991). TEMP_CELSIUS is a deprecated constant that was removed in HA Core 2025.1.  Notes use of UnitOfTemperature.CELSIUS instead...

**Comment by Jobsa** [comment]
SOLVED -- Changed integration to HACS version forked by @dwradcliffe.  [His version](https://github.com/dwradcliffe/intellicenter) had solved the TEMP_CELSIUS problem...
