### PR TITLE
Fix compatibility with HA 2025.8+

### PR DESCRIPTION
**Pull request by paragbatavia**
This integration stopped working for me quite a while ago. The integration would load, but no entities would show up. Finally dug into it to understand why. It seems to be working now, but since it's winter where I am, I haven't been able to test it fully. 

- Replace removed async_forward_entry_setup/unload with async_forward_entry_setups/async_unload_platforms
- Replace removed HomeAssistantType with HomeAssistant from homeassistant.core
- Remove removed DEFAULT_MIN/MAX_VALUE/STEP constants from number.py

### CODE REVIEW

**Comment by bbellwfu** [comment]
Confirming this PR works on HA 2026.4.1 against IntelliCenter firmware `IC: 2.026 / ICWEB: 2024-06-10 2.026`.

I hit the exact same symptoms before finding this PR: integration would load, model would populate (`model now contains 46 objects`), but zero entities created. The underlying `ImportError: cannot import name 'HomeAssistantType' from 'homeassistant.helpers.typing'` was completely silent because `setup_platforms()` is fired via `hass.async_create_task(...)` without ever being awaited, so the platform-load failure gets swallowed.

I applied the three fixes from this PR manually and got 35 entities created cleanly:
- 5 switches (Pool, Spa, Jets, Spillway, Vacation Mode)
- 2 water heaters (Pool, Spa, both wired to a shared MasterTemp)
- 1 light (IntelliBrite)
- 6 pump sensors (RPM/GPM/Power for both VSF pumps)
- 4 body temperature sensors
- 8 schedule binary sensors
- + freeze, MasterTemp status, environment sensors, etc.

Live data is flowing correctly — pump RPM/GPM/power update in near real-time via NotifyList messages, switches actuate the actual pool circuits, water_heater entities reflect MasterTemp targets.

One additional debug-friendly tweak that helped me track this down: wrapping the `await async_forward_entry_setups(...)` call in a `try/except Exception` with `_LOGGER.exception(...)` would have surfaced the underlying ImportError immediately instead of being silently dropped. Up to you whether that's worth adding here, but it would save the next person hours of head-scratching.

Thanks @paragbatavia for the PR. @jlvaillant — any chance of a review/merge? This integration is otherwise dead on any modern HA install.
